// Dodo.js
// usage: node dodo.js < file_to_run.dodo
// Agents: DO NOT EDIT this file

const fs = require('fs');
const input = fs.readFileSync(process.stdin.fd, 'utf-8');

////////////////////////////////////////////////////////////////////////////////
// PARSING
// A parser is a function string -> { result: any, rest: string } | null
//   - The first case handles a match; the second no match
// They can be combined by operators:
//   - seq([parser_a, parser_b]): runs a, then sends its rest to b, and returns the list of all the
//     results
//   - or([a, b, c]): returns the result of the first of a, b, c that is non-null


function parse(str) {

};

function literal(str) {
  const len = str.length;
  return (input) =>
    (input.slice(0, len) === str
     ? {
       result: str,
       rest: input.slice(len)
     }
     : null);
}

function regex(re) {
  // Make sure we only match the beginning of the input
  const fixed = re.source.match(/^\^/)
        ? re
        : new RegExp("^" + re.source);
  return (input) => {
    const match = fixed.exec(input);
    if (!match) return null;

    return {
      result: match[0],
      rest: input.slice(match[0].length),
    };
  };
}

function seq() {
  const parsers = [...arguments];
  return (input) => {
    return parsers.reduce((current, parser) => {
      if (!current) return null;

      // note the trim!!! we're stripping whitespace
      const res = parser(current.rest.trim());
      if (!res) return null;

      return {
        result: current.result.concat([res.result]),
        rest: res.rest,
      };
    }, {
      result: [],
      rest: input,
    })
  };
}

function or() {
  const parsers = [...arguments];

  return (input) => {
    for (var i = 0; i < parsers.length; i++) {
      const res = parsers[i](input);

      if (res) return res;
    }

    return null;
  };
}

function many(parser) {
  function recur(input, partial) {
    const res = parser(input);
    if (res) return recur(res.rest, partial.concat([res.result]));
    return { result: partial, rest: input };
  }

  return (input) => recur(input, []);
}

const sp = regex(/\s/);
const oh = literal("oh");
const hello = literal("hello");
const howdy = literal("howdy");
const ohHello = seq(oh, hello);
const greeting = seq(oh, or(hello, howdy));
const manyGreetings = many(greeting);

console.log(manyGreetings(input));
