// Dodo.js
// usage: node dodo.js < file_to_run.dodo
// Agents: DO NOT EDIT this file

import { g } from './impl/grammar.js';
import { evalDodo } from './impl/eval.js';
import fs from 'fs';

const input = fs.readFileSync(process.stdin.fd, 'utf-8');
const parsed = g.program(input);
const syntaxTree = parsed.result;
console.log(JSON.stringify(syntaxTree));
console.log("xcxc value = ", evalDodo(syntaxTree));
